### ISSUE TITLE
Request, ASC lookup table for variable genes

### ISSUE THREAD

**Issue by dduchen** [MuteJester/GenAIRR#1]
Great tool! For downstream use/testing purposes with the simulated sequences generated by GenAIRR, would it be possible to provide the ASC table you use linking the simulated IGHVF... alleles to the potential matching IMGT/OGRDB formatted IGHV allele nomenclature?
Or if this information is included somewhere, where can it be found?
Thanks for your time and work on this!

**Comment by MuteJester** [comment]
Hey Delan!

Glad to hear you found GenAIRR useful! We've made some recent improvements, which are now available in the latest release on PyPI (GenAIRR 0.1.4). This update includes various enhancements, and you can now easily access the table that maps ASC's to IMGT names via the dataconfig object used to generate your sequences.

Here's how you can do it:

```python 
from GenAIRR.data import builtin_heavy_chain_data_config

dataconfig = builtin_heavy_chain_data_config()
# Access the ASC to IMGT mapping table
asc_table = dataconfig.asc_tables['V']
```
In this pandas DataFrame, the "new_allele" column contains the ASC IGHVF naming scheme, and the "imgt_allele" column provides the corresponding IMGT allele.

To ensure you have the latest features, please update GenAIRR from version 0.1.3 to 0.1.4. If you need any further assistance or have more questions, feel free to reach out.

Additionally, we'll soon be uploading detailed documentation to make it even easier to use GenAIRR.

Thanks for your time and support!
